services:
  frontend:
    labels:
      - traefik.enable=true
        #      - traefik.docker.network=traefik-public
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=http
#      - traefik.http.routers.frontend-http.rule=HostRegexp(`{any:.+}`)
      - traefik.http.routers.frontend-http.rule=Host(`dev.cms.ontum.co`)
              # ${ROUTER}-http to use the middleware to redirect to https
      - traefik.http.routers.frontend-http.middlewares=https-redirect
      # ${ROUTER}-https the actual router using HTTPS
      # Uses the environment variable SITES
      - traefik.http.routers.frontend-https.rule=Host(`dev.cms.ontum.co`)
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.tls=true
      # Use the service ${ROUTER} with the frontend
      - traefik.http.routers.frontend-https.service=frontend
      # Use the "le" (Let's Encrypt) resolver created below
      - traefik.http.routers.frontend-https.tls.certresolver=le

        #networks:
        #traefik-public:
        # external: true
