services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=8080
      - traefik.http.routers.frontend-http.entrypoints=web
        ## Add domains for frappe sites:
        #original conf
#      - traefik.http.routers.frontend-http.rule=HostRegexp(`{any:.+}`)
#      Modified
#      - traefik.http.routers.frontend-http.rule=Host(`dev.cms.ontum.co`)
#      With ENV variable
      - traefik.http.routers.frontend-http.rule=Host(`${ONTUM_DOMAIN:?No ONTUM_DOMAIN set}`)
  proxy:
    image: traefik:2.5
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    userns_mode: host
